export enum GameType {
  START_GAME = 'START_GAME',
  TOGGLE_FLAG = 'TOGGLE_FLAG',
  REVEAL_CELL = 'REVEAL_CELL',
  UNDO_LOOSING_MOVE = 'UNDO_LOOSING_MOVE',
  TICK_TIMER = 'TICK_TIMER',
  LOAD_GAME = 'LOAD_GAME',
}
